author = "mregger"
baseURL = "https://kontor.ca"
canonifyURLs = true
languageCode = "en-us"
theme = "kontor-theme"
title = "Kontor Development Blog"

[parms]
  google_analytics_id="UA-156253687-1"
  
